CREATE TABLE FORMA_PAGAMENTO (
	ID INTEGER IDENTITY PRIMARY KEY,
	FORMA VARCHAR(300) NOT NULL
);

CREATE TABLE STATUS_PRODUTO (
	ID INTEGER IDENTITY PRIMARY KEY,
	STATUS VARCHAR(50) NOT NULL
);

ALTER TABLE PRODUTO
ADD IMAGEM BLOB;
